name: 'Goodcheck+Reviewdog Action'
description: 'Analyze code statically using Goodcheck in Github actions and show errors as comments on the PR'
runs:
  using: "composite"
  steps:
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
    - name: Setup Reviewdog
      if: github.event_name == 'pull_request'
      uses: reviewdog/action-setup@v1
    - name: Install Goodcheck
      run: gem install goodcheck
      shell: bash
    - name: Run Goodcheck passing errors to Reviewdog
      if: github.event_name == 'pull_request'
      run: 'goodcheck check | reviewdog -efm="%f:%l:%c: %m" -diff="git diff FETCH_HEAD"'
      shell: bash
    - name: Run Goodcheck
      if: github.event_name != 'pull_request'
      run: 'goodcheck check'
      shell: bash