name: 'Goodcheck Action'
description: 'Analyze code statically using Goodcheck in Github actions'
runs:
  using: "composite"
  steps:
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
    - run: gem install goodcheck
      shell: bash
    - run: goodcheck check
      shell: bash